/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../../pages/__root'
import { Route as AboutRouteImport } from './../../../pages/about'
import { Route as Header_layoutRouteRouteImport } from './../../../pages/_header_layout/route'
import { Route as Header_layoutmapIndexRouteImport } from './../../../pages/_header_layout/(map)/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const Header_layoutRouteRoute = Header_layoutRouteRouteImport.update({
  id: '/_header_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const Header_layoutmapIndexRoute = Header_layoutmapIndexRouteImport.update({
  id: '/(map)/',
  path: '/',
  getParentRoute: () => Header_layoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/': typeof Header_layoutmapIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/': typeof Header_layoutmapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_header_layout': typeof Header_layoutRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_header_layout/(map)/': typeof Header_layoutmapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/'
  id: '__root__' | '/_header_layout' | '/about' | '/_header_layout/(map)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Header_layoutRouteRoute: typeof Header_layoutRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header_layout': {
      id: '/_header_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Header_layoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header_layout/(map)/': {
      id: '/_header_layout/(map)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Header_layoutmapIndexRouteImport
      parentRoute: typeof Header_layoutRouteRoute
    }
  }
}

interface Header_layoutRouteRouteChildren {
  Header_layoutmapIndexRoute: typeof Header_layoutmapIndexRoute
}

const Header_layoutRouteRouteChildren: Header_layoutRouteRouteChildren = {
  Header_layoutmapIndexRoute: Header_layoutmapIndexRoute,
}

const Header_layoutRouteRouteWithChildren =
  Header_layoutRouteRoute._addFileChildren(Header_layoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Header_layoutRouteRoute: Header_layoutRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
