/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../../pages/__root'
import { Route as AboutRouteImport } from './../../../pages/about'
import { Route as Header_layoutRouteRouteImport } from './../../../pages/_header_layout/route'
import { Route as LoginIndexRouteImport } from './../../../pages/login/index'
import { Route as AdminIndexRouteImport } from './../../../pages/admin/index'
import { Route as StoresStoreIdRouteImport } from './../../../pages/stores/$storeId'
import { Route as Header_layoutMyReviewsRouteImport } from './../../../pages/_header_layout/my-reviews'
import { Route as Header_layoutTradesIndexRouteImport } from './../../../pages/_header_layout/trades/index'
import { Route as Header_layoutProfileIndexRouteImport } from './../../../pages/_header_layout/profile/index'
import { Route as Header_layoutmapIndexRouteImport } from './../../../pages/_header_layout/(map)/index'
import { Route as Header_layoutTradesNewRouteImport } from './../../../pages/_header_layout/trades/new'
import { Route as AuthKakaoCallbackIndexRouteImport } from './../../../pages/auth/kakao/callback/index'
import { Route as Header_layoutTradesChatsIndexRouteImport } from './../../../pages/_header_layout/trades/chats/index'
import { Route as Header_layoutTradesTradeIdIndexRouteImport } from './../../../pages/_header_layout/trades/$tradeId/index'
import { Route as Header_layoutTradesTradeIdEditRouteImport } from './../../../pages/_header_layout/trades/$tradeId/edit'
import { Route as Header_layoutTradesTradeIdChatRoomChatRoomIdRouteImport } from './../../../pages/_header_layout/trades/$tradeId/chat-room/$chatRoomId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const Header_layoutRouteRoute = Header_layoutRouteRouteImport.update({
  id: '/_header_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const Header_layoutMyReviewsRoute = Header_layoutMyReviewsRouteImport.update({
  id: '/my-reviews',
  path: '/my-reviews',
  getParentRoute: () => Header_layoutRouteRoute,
} as any)
const Header_layoutTradesIndexRoute =
  Header_layoutTradesIndexRouteImport.update({
    id: '/trades/',
    path: '/trades/',
    getParentRoute: () => Header_layoutRouteRoute,
  } as any)
const Header_layoutProfileIndexRoute =
  Header_layoutProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => Header_layoutRouteRoute,
  } as any)
const Header_layoutmapIndexRoute = Header_layoutmapIndexRouteImport.update({
  id: '/(map)/',
  path: '/',
  getParentRoute: () => Header_layoutRouteRoute,
} as any)
const Header_layoutTradesNewRoute = Header_layoutTradesNewRouteImport.update({
  id: '/trades/new',
  path: '/trades/new',
  getParentRoute: () => Header_layoutRouteRoute,
} as any)
const AuthKakaoCallbackIndexRoute = AuthKakaoCallbackIndexRouteImport.update({
  id: '/auth/kakao/callback/',
  path: '/auth/kakao/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const Header_layoutTradesChatsIndexRoute =
  Header_layoutTradesChatsIndexRouteImport.update({
    id: '/trades/chats/',
    path: '/trades/chats/',
    getParentRoute: () => Header_layoutRouteRoute,
  } as any)
const Header_layoutTradesTradeIdIndexRoute =
  Header_layoutTradesTradeIdIndexRouteImport.update({
    id: '/trades/$tradeId/',
    path: '/trades/$tradeId/',
    getParentRoute: () => Header_layoutRouteRoute,
  } as any)
const Header_layoutTradesTradeIdEditRoute =
  Header_layoutTradesTradeIdEditRouteImport.update({
    id: '/trades/$tradeId/edit',
    path: '/trades/$tradeId/edit',
    getParentRoute: () => Header_layoutRouteRoute,
  } as any)
const Header_layoutTradesTradeIdChatRoomChatRoomIdRoute =
  Header_layoutTradesTradeIdChatRoomChatRoomIdRouteImport.update({
    id: '/trades/$tradeId/chat-room/$chatRoomId',
    path: '/trades/$tradeId/chat-room/$chatRoomId',
    getParentRoute: () => Header_layoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/my-reviews': typeof Header_layoutMyReviewsRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/trades/new': typeof Header_layoutTradesNewRoute
  '/': typeof Header_layoutmapIndexRoute
  '/profile': typeof Header_layoutProfileIndexRoute
  '/trades': typeof Header_layoutTradesIndexRoute
  '/trades/$tradeId/edit': typeof Header_layoutTradesTradeIdEditRoute
  '/trades/$tradeId': typeof Header_layoutTradesTradeIdIndexRoute
  '/trades/chats': typeof Header_layoutTradesChatsIndexRoute
  '/auth/kakao/callback': typeof AuthKakaoCallbackIndexRoute
  '/trades/$tradeId/chat-room/$chatRoomId': typeof Header_layoutTradesTradeIdChatRoomChatRoomIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/my-reviews': typeof Header_layoutMyReviewsRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/trades/new': typeof Header_layoutTradesNewRoute
  '/': typeof Header_layoutmapIndexRoute
  '/profile': typeof Header_layoutProfileIndexRoute
  '/trades': typeof Header_layoutTradesIndexRoute
  '/trades/$tradeId/edit': typeof Header_layoutTradesTradeIdEditRoute
  '/trades/$tradeId': typeof Header_layoutTradesTradeIdIndexRoute
  '/trades/chats': typeof Header_layoutTradesChatsIndexRoute
  '/auth/kakao/callback': typeof AuthKakaoCallbackIndexRoute
  '/trades/$tradeId/chat-room/$chatRoomId': typeof Header_layoutTradesTradeIdChatRoomChatRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_header_layout': typeof Header_layoutRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_header_layout/my-reviews': typeof Header_layoutMyReviewsRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_header_layout/trades/new': typeof Header_layoutTradesNewRoute
  '/_header_layout/(map)/': typeof Header_layoutmapIndexRoute
  '/_header_layout/profile/': typeof Header_layoutProfileIndexRoute
  '/_header_layout/trades/': typeof Header_layoutTradesIndexRoute
  '/_header_layout/trades/$tradeId/edit': typeof Header_layoutTradesTradeIdEditRoute
  '/_header_layout/trades/$tradeId/': typeof Header_layoutTradesTradeIdIndexRoute
  '/_header_layout/trades/chats/': typeof Header_layoutTradesChatsIndexRoute
  '/auth/kakao/callback/': typeof AuthKakaoCallbackIndexRoute
  '/_header_layout/trades/$tradeId/chat-room/$chatRoomId': typeof Header_layoutTradesTradeIdChatRoomChatRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/my-reviews'
    | '/stores/$storeId'
    | '/admin'
    | '/login'
    | '/trades/new'
    | '/'
    | '/profile'
    | '/trades'
    | '/trades/$tradeId/edit'
    | '/trades/$tradeId'
    | '/trades/chats'
    | '/auth/kakao/callback'
    | '/trades/$tradeId/chat-room/$chatRoomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/my-reviews'
    | '/stores/$storeId'
    | '/admin'
    | '/login'
    | '/trades/new'
    | '/'
    | '/profile'
    | '/trades'
    | '/trades/$tradeId/edit'
    | '/trades/$tradeId'
    | '/trades/chats'
    | '/auth/kakao/callback'
    | '/trades/$tradeId/chat-room/$chatRoomId'
  id:
    | '__root__'
    | '/_header_layout'
    | '/about'
    | '/_header_layout/my-reviews'
    | '/stores/$storeId'
    | '/admin/'
    | '/login/'
    | '/_header_layout/trades/new'
    | '/_header_layout/(map)/'
    | '/_header_layout/profile/'
    | '/_header_layout/trades/'
    | '/_header_layout/trades/$tradeId/edit'
    | '/_header_layout/trades/$tradeId/'
    | '/_header_layout/trades/chats/'
    | '/auth/kakao/callback/'
    | '/_header_layout/trades/$tradeId/chat-room/$chatRoomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Header_layoutRouteRoute: typeof Header_layoutRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  StoresStoreIdRoute: typeof StoresStoreIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  AuthKakaoCallbackIndexRoute: typeof AuthKakaoCallbackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header_layout': {
      id: '/_header_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Header_layoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header_layout/my-reviews': {
      id: '/_header_layout/my-reviews'
      path: '/my-reviews'
      fullPath: '/my-reviews'
      preLoaderRoute: typeof Header_layoutMyReviewsRouteImport
      parentRoute: typeof Header_layoutRouteRoute
    }
    '/_header_layout/trades/': {
      id: '/_header_layout/trades/'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof Header_layoutTradesIndexRouteImport
      parentRoute: typeof Header_layoutRouteRoute
    }
    '/_header_layout/profile/': {
      id: '/_header_layout/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof Header_layoutProfileIndexRouteImport
      parentRoute: typeof Header_layoutRouteRoute
    }
    '/_header_layout/(map)/': {
      id: '/_header_layout/(map)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Header_layoutmapIndexRouteImport
      parentRoute: typeof Header_layoutRouteRoute
    }
    '/_header_layout/trades/new': {
      id: '/_header_layout/trades/new'
      path: '/trades/new'
      fullPath: '/trades/new'
      preLoaderRoute: typeof Header_layoutTradesNewRouteImport
      parentRoute: typeof Header_layoutRouteRoute
    }
    '/auth/kakao/callback/': {
      id: '/auth/kakao/callback/'
      path: '/auth/kakao/callback'
      fullPath: '/auth/kakao/callback'
      preLoaderRoute: typeof AuthKakaoCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header_layout/trades/chats/': {
      id: '/_header_layout/trades/chats/'
      path: '/trades/chats'
      fullPath: '/trades/chats'
      preLoaderRoute: typeof Header_layoutTradesChatsIndexRouteImport
      parentRoute: typeof Header_layoutRouteRoute
    }
    '/_header_layout/trades/$tradeId/': {
      id: '/_header_layout/trades/$tradeId/'
      path: '/trades/$tradeId'
      fullPath: '/trades/$tradeId'
      preLoaderRoute: typeof Header_layoutTradesTradeIdIndexRouteImport
      parentRoute: typeof Header_layoutRouteRoute
    }
    '/_header_layout/trades/$tradeId/edit': {
      id: '/_header_layout/trades/$tradeId/edit'
      path: '/trades/$tradeId/edit'
      fullPath: '/trades/$tradeId/edit'
      preLoaderRoute: typeof Header_layoutTradesTradeIdEditRouteImport
      parentRoute: typeof Header_layoutRouteRoute
    }
    '/_header_layout/trades/$tradeId/chat-room/$chatRoomId': {
      id: '/_header_layout/trades/$tradeId/chat-room/$chatRoomId'
      path: '/trades/$tradeId/chat-room/$chatRoomId'
      fullPath: '/trades/$tradeId/chat-room/$chatRoomId'
      preLoaderRoute: typeof Header_layoutTradesTradeIdChatRoomChatRoomIdRouteImport
      parentRoute: typeof Header_layoutRouteRoute
    }
  }
}

interface Header_layoutRouteRouteChildren {
  Header_layoutMyReviewsRoute: typeof Header_layoutMyReviewsRoute
  Header_layoutTradesNewRoute: typeof Header_layoutTradesNewRoute
  Header_layoutmapIndexRoute: typeof Header_layoutmapIndexRoute
  Header_layoutProfileIndexRoute: typeof Header_layoutProfileIndexRoute
  Header_layoutTradesIndexRoute: typeof Header_layoutTradesIndexRoute
  Header_layoutTradesTradeIdEditRoute: typeof Header_layoutTradesTradeIdEditRoute
  Header_layoutTradesTradeIdIndexRoute: typeof Header_layoutTradesTradeIdIndexRoute
  Header_layoutTradesChatsIndexRoute: typeof Header_layoutTradesChatsIndexRoute
  Header_layoutTradesTradeIdChatRoomChatRoomIdRoute: typeof Header_layoutTradesTradeIdChatRoomChatRoomIdRoute
}

const Header_layoutRouteRouteChildren: Header_layoutRouteRouteChildren = {
  Header_layoutMyReviewsRoute: Header_layoutMyReviewsRoute,
  Header_layoutTradesNewRoute: Header_layoutTradesNewRoute,
  Header_layoutmapIndexRoute: Header_layoutmapIndexRoute,
  Header_layoutProfileIndexRoute: Header_layoutProfileIndexRoute,
  Header_layoutTradesIndexRoute: Header_layoutTradesIndexRoute,
  Header_layoutTradesTradeIdEditRoute: Header_layoutTradesTradeIdEditRoute,
  Header_layoutTradesTradeIdIndexRoute: Header_layoutTradesTradeIdIndexRoute,
  Header_layoutTradesChatsIndexRoute: Header_layoutTradesChatsIndexRoute,
  Header_layoutTradesTradeIdChatRoomChatRoomIdRoute:
    Header_layoutTradesTradeIdChatRoomChatRoomIdRoute,
}

const Header_layoutRouteRouteWithChildren =
  Header_layoutRouteRoute._addFileChildren(Header_layoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Header_layoutRouteRoute: Header_layoutRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  StoresStoreIdRoute: StoresStoreIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  AuthKakaoCallbackIndexRoute: AuthKakaoCallbackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
